// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scene_messages.proto

#ifndef PROTOBUF_scene_5fmessages_2eproto__INCLUDED
#define PROTOBUF_scene_5fmessages_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace common {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_scene_5fmessages_2eproto();
void protobuf_AssignDesc_scene_5fmessages_2eproto();
void protobuf_ShutdownFile_scene_5fmessages_2eproto();

class scene_enter;
class scene_move;

// ===================================================================

class scene_enter : public ::google::protobuf::Message {
 public:
  scene_enter();
  virtual ~scene_enter();

  scene_enter(const scene_enter& from);

  inline scene_enter& operator=(const scene_enter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const scene_enter& default_instance();

  void Swap(scene_enter* other);

  // implements Message ----------------------------------------------

  scene_enter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const scene_enter& from);
  void MergeFrom(const scene_enter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 last_scene_id = 1;
  inline bool has_last_scene_id() const;
  inline void clear_last_scene_id();
  static const int kLastSceneIdFieldNumber = 1;
  inline ::google::protobuf::int32 last_scene_id() const;
  inline void set_last_scene_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:common.scene_enter)
 private:
  inline void set_has_last_scene_id();
  inline void clear_has_last_scene_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 last_scene_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_scene_5fmessages_2eproto();
  friend void protobuf_AssignDesc_scene_5fmessages_2eproto();
  friend void protobuf_ShutdownFile_scene_5fmessages_2eproto();

  void InitAsDefaultInstance();
  static scene_enter* default_instance_;
};
// -------------------------------------------------------------------

class scene_move : public ::google::protobuf::Message {
 public:
  scene_move();
  virtual ~scene_move();

  scene_move(const scene_move& from);

  inline scene_move& operator=(const scene_move& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const scene_move& default_instance();

  void Swap(scene_move* other);

  // implements Message ----------------------------------------------

  scene_move* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const scene_move& from);
  void MergeFrom(const scene_move& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 target_x = 1;
  inline bool has_target_x() const;
  inline void clear_target_x();
  static const int kTargetXFieldNumber = 1;
  inline ::google::protobuf::int32 target_x() const;
  inline void set_target_x(::google::protobuf::int32 value);

  // required int32 target_y = 2;
  inline bool has_target_y() const;
  inline void clear_target_y();
  static const int kTargetYFieldNumber = 2;
  inline ::google::protobuf::int32 target_y() const;
  inline void set_target_y(::google::protobuf::int32 value);

  // required int32 target_z = 3;
  inline bool has_target_z() const;
  inline void clear_target_z();
  static const int kTargetZFieldNumber = 3;
  inline ::google::protobuf::int32 target_z() const;
  inline void set_target_z(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:common.scene_move)
 private:
  inline void set_has_target_x();
  inline void clear_has_target_x();
  inline void set_has_target_y();
  inline void clear_has_target_y();
  inline void set_has_target_z();
  inline void clear_has_target_z();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 target_x_;
  ::google::protobuf::int32 target_y_;
  ::google::protobuf::int32 target_z_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_scene_5fmessages_2eproto();
  friend void protobuf_AssignDesc_scene_5fmessages_2eproto();
  friend void protobuf_ShutdownFile_scene_5fmessages_2eproto();

  void InitAsDefaultInstance();
  static scene_move* default_instance_;
};
// ===================================================================


// ===================================================================

// scene_enter

// required int32 last_scene_id = 1;
inline bool scene_enter::has_last_scene_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void scene_enter::set_has_last_scene_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void scene_enter::clear_has_last_scene_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void scene_enter::clear_last_scene_id() {
  last_scene_id_ = 0;
  clear_has_last_scene_id();
}
inline ::google::protobuf::int32 scene_enter::last_scene_id() const {
  return last_scene_id_;
}
inline void scene_enter::set_last_scene_id(::google::protobuf::int32 value) {
  set_has_last_scene_id();
  last_scene_id_ = value;
}

// -------------------------------------------------------------------

// scene_move

// required int32 target_x = 1;
inline bool scene_move::has_target_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void scene_move::set_has_target_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void scene_move::clear_has_target_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void scene_move::clear_target_x() {
  target_x_ = 0;
  clear_has_target_x();
}
inline ::google::protobuf::int32 scene_move::target_x() const {
  return target_x_;
}
inline void scene_move::set_target_x(::google::protobuf::int32 value) {
  set_has_target_x();
  target_x_ = value;
}

// required int32 target_y = 2;
inline bool scene_move::has_target_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void scene_move::set_has_target_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void scene_move::clear_has_target_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void scene_move::clear_target_y() {
  target_y_ = 0;
  clear_has_target_y();
}
inline ::google::protobuf::int32 scene_move::target_y() const {
  return target_y_;
}
inline void scene_move::set_target_y(::google::protobuf::int32 value) {
  set_has_target_y();
  target_y_ = value;
}

// required int32 target_z = 3;
inline bool scene_move::has_target_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void scene_move::set_has_target_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void scene_move::clear_has_target_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void scene_move::clear_target_z() {
  target_z_ = 0;
  clear_has_target_z();
}
inline ::google::protobuf::int32 scene_move::target_z() const {
  return target_z_;
}
inline void scene_move::set_target_z(::google::protobuf::int32 value) {
  set_has_target_z();
  target_z_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace common

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_scene_5fmessages_2eproto__INCLUDED
